name: Daily Commit

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update log file
      run: |
        echo "Commit on $(date)" >> log.txt

    - name: Commit changes
      run: |
        # Set the Git user details (Good job including this!)
        git config --global user.name "Dakshaaaaa"
        git config --global user.email "dakshapawar0603@gmail.com"
        
        
        git add log.txt
        
        git commit -m "Daily commit $(date)" 
        
        
        git push
